name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
jobs:

  build:
    runs-on: self-hosted
    steps:
    - shell: pwsh
    - run: iisreset /stop
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7'
    - run: dotnet build api-infow
    - run: dotnet publish api-infow
    - shell: pwsh
    - run: iisreset /start 
