
name: Run commands on different operating systems
on:
  push:
    branches: [ main ]

jobs:
  Run-PSScriptAnalyzer-on-Windows:
    name: Run on Windows
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7'
      - shell: pwsh
        run: |
          iisreset /stop
      - name: build api info
        shell: pwsh
        run: |
          dotnet build api-infow
      - name: punlish api info
        shell: pwsh
        run: |
          dotnet publish api-infow
